#!/usr/bin/env zsh

#export PATH=$PATH:~/.npm/bin
#export PATH=$PATH:~/.yarn/bin
#export PATH=$PATH:~/.local/bin
#export PATH=$PATH:$HOME/dev/bin
#export ERL_AFLAGS="-kernel shell_history enabled"
#export EDITOR=nvim
#export BROWSER=google-chrome-stable
#export GOPATH=/home/thdxr/dev/gopath

#export XDG_CONFIG_HOME=$HOME/.config
#export XDG_CACHE_HOME=$HOME/.cache
#export XDG_DOWNLOADS=$HOME/downloads
#export XDG_DATA_HOME=$HOME/.local/share
#export XDG_STATE_HOME=$HOME/.local/state

